apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-scanner
  namespace: trader-dev
  labels:
    app: go-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-scanner
  template:
    metadata:
      labels:
        app: go-scanner
    spec:
      containers:
      - name: go-scanner
        image: ${DOCKERHUB_USERNAME}/go-scanner:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-scanner
  namespace: trader-dev
spec:
  selector:
    app: go-scanner
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 