apiVersion: v1
kind: Service
metadata:
  name: python-orch
  labels:
    app: python-orch
    component: ibkr-trader
spec:
  type: ClusterIP
  selector:
    app: python-orch
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: grpc
    port: 50051
    targetPort: grpc 