apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-orch
  labels:
    app: python-orch
    component: ibkr-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-orch
  template:
    metadata:
      labels:
        app: python-orch
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: python-orch
        image: ${REGISTRY:-localhost:5000}/python-orch:latest
        imagePullPolicy: IfNotPresent
        args: ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: CONFIG_PATH
          value: "/app/config.yaml"
        - name: REDIS_URL
          value: "redis://redis:6379"
        ports:
        - name: http
          containerPort: 8000
        - name: grpc
          containerPort: 50051
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: trader-config
          items:
          - key: config.yaml
            path: config.yaml 