apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app: redis
    component: ibkr-trader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 