apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-orchestrator
  namespace: trader-prod
  labels:
    app: python-orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-orchestrator
  template:
    metadata:
      labels:
        app: python-orchestrator
    spec:
      containers:
      - name: python-orchestrator
        image: ${DOCKERHUB_USERNAME}/python-orchestrator:latest
        ports:
        - containerPort: 8000
        env:
        - name: IBKR_HOST
          value: "tws-gateway-prod"
        - name: IBKR_PORT
          value: "7497"
        - name: IBKR_CLIENT_ID
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-orchestrator
  namespace: trader-prod
spec:
  selector:
    app: python-orchestrator
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 