// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectIBKR(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectIBKR'](arg1, arg2, arg3);
}

export function GetConfigSchema() {
  return window['go']['main']['App']['GetConfigSchema']();
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
