// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectIBKR(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetConfigSchema():Promise<string>;

export function GetCurrentConfig():Promise<string>;

export function GetDefaultConfig():Promise<string>;

export function GetPositions():Promise<Array<main.Position>>;

export function GetVersion():Promise<string>;

export function PauseScanning():Promise<boolean>;

export function ResumeScanning():Promise<boolean>;

export function ScanSignals():Promise<Array<main.Signal>>;

export function Status():Promise<string>;

export function UpdateConfig(arg1:string):Promise<boolean>;
