apiVersion: v1
kind: ConfigMap
metadata:
  name: trader-config
  namespace: {{ .Values.namespace }}
  labels:
    app: ibkr-trader
    {{- include "traderadmin.labels" . | nindent 4 }}
data:
  config.yaml: |
    ibkr:
      host: "{{ .Values.config.python.ibkr.host }}"
      port: {{ .Values.config.python.ibkr.port }}
      client_id: {{ .Values.config.python.ibkr.client_id }}
    strategy:
      sma_period: {{ .Values.config.python.strategy.sma_period }}
      candle_count: {{ .Values.config.python.strategy.candle_count }}
      otm_offset: {{ .Values.config.python.strategy.otm_offset }}
      iv_threshold: {{ .Values.config.python.strategy.iv_threshold }}
      min_reward_risk: {{ .Values.config.python.strategy.min_reward_risk }}
  config.json: |
    {
      "sma_period": {{ .Values.config.scanner.sma_period }},
      "candle_count": {{ .Values.config.scanner.candle_count }},
      "iv_threshold": {{ .Values.config.scanner.iv_threshold }},
      "min_reward_risk": {{ .Values.config.scanner.min_reward_risk }},
      "universe": [{{ range $i, $e := .Values.config.scanner.universe }}{{ if $i }}, {{ end }}"{{ $e }}"{{ end }}]
    } 