apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.redis.type }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
  - name: redis
    port: {{ .Values.service.redis.port }}
    targetPort: redis 