name: Kubernetes Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'
      - '.github/workflows/k8s-deploy.yml'
  workflow_run:
    workflows: ["Python Orchestrator CI/CD", "Go Scanner CI/CD"]
    types:
      - completed
    branches: [main]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.DEV_KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Deploy to development
        run: |
          kubectl apply -f k8s/dev/

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    environment:
      name: production
      url: https://trader-admin-prod.example.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.PROD_KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Deploy to production
        run: |
          kubectl apply -f k8s/prod/ 